version: "3.8"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: aimvector/zookeeper:2.7.0
    build:
      context: ./zookeeper
    volumes:
      - ./config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
      - ./data/zookeeper-1/:/tmp/zookeeper/
    networks:
      - kafka

  kafka-1:
    container_name: kafka-1
    image: aimvector/kafka:2.7.0
    build:
      context: .
    volumes:
      - ./config/kafka-1/server.properties:/kafka/config/server.properties
      - ./data/kafka-1/:/tmp/kafka-logs/
    networks:
      - kafka

  kafka-consumer-node:
    container_name: kafka-consumer-node
    image: aimvector/kafka-consumer-node:1.0.0
    build:
      context: ./applications/consumer
    networks:
      - kafka

  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:7.15.1
    ports:
      - "10000:10000"
    volumes:
      - ./logstash/settings/:/usr/share/logstash/config/
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    container_name: logstash
    networks:
      - kafka
      - eknetwork

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.2"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=somethingsecret
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - logger.level=WARN
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - eknetwork

  kibana:
    depends_on:
      - elasticsearch
    image: "docker.elastic.co/kibana/kibana:7.13.2"
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=somethingsecret
    networks:
      - eknetwork

networks:
  kafka:
    name: kafka
  eknetwork:
    driver: bridge
